spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307/twitterdb
#    username: dev
#    password: dev123
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true